### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by CaiYiLiang** [FreeCodeCamp-Guangzhou/FreeCodeCamp-Guangzhou.github.io#3]
以下几点是建议，提供brain storm和意见，旨在建立一个更加完善和更利于开放给其他小伙伴的项目。
- README 中的任务## Develop Tips ，##TODOLIST 分到TODOS.md中,并且谁领了任务就把自己的名字、日期和on status加上。
- README 中写feature介绍，如何搭建环境，需要Node,python环境,npm install etc.
- 因为计划到先建立Home.vue和贡献墙（后续会一起讨论这个机制），之后会开放到给FCC广州群的各位，所以技术栈上建议考虑到大众点的情况，是不是必须用scss，是不是必须用更复杂的去构建这两个单页面。
- 父子Component尽量写注释。

**Comment by Akiq2016** [comment]
1、 你可以改。
2、好像也没啥环境 就npm install,npm run dev ,npm start啊之类的 ，可以在package.json里面看。
3、肯定不会只有这两个页面，要做干货之类等技术分享页面，做这个网站不能纯看一些无聊的介绍吧。并不是一定需要scss，可以写普通的css，这个不是问题，你在scss里写css也是一样的呀。不需要更复杂，哪怕用最简单的html+css也是能很快的写出这两个页面，选择vue其实提供大家练手的机会而已，使用vue2+webpack1+es6足够了，如果打算扩展的话以后可以弄后台，使用nodejs+mysql诸如此类去扩展。
4、之后可以考虑把组件功能完善化，组件拿出来分享使用，所以注释尽量完善。
